### PR TITLE
Add Animated movie card

### PR DESCRIPTION
**Pull request by AnshMeshram**
Contributing with my piece of art to the project :)
I hope you apperciate my art
please accept the pull request

### CODE REVIEW

**Comment by LaurelineP** [comment]
Thanks for your contribution 🙌
Before we could merge your contribution, the following feedbacks need to be addressed first.
Please address the given feedbacks

# Feedbacks  
Missing the pictural representation of your animation and details in `include.js` file
- [ ] missing pictural representation
- [ ] missing `include.js` contributions

## Acceptance criteria for a contribution
- [x] the contribution includes a new folder named after the author github user name  in `./Art`
- [x] the contribution includes an HTML file
    - [x] no CSS
    - [x] no JS
    - [x] no embedded  SVG 
    - [x] has a `<link>` tag to the CSS file
- [x] the contribution includes a CSS file
- [ ] the contribution includes the animated file (gif) or picture (jpeg, jpg, png )
    _the pictural representation must not include the browser frame, just the animation_
- [ ] the contribution includes the correct contribution's details in `include.js`

Please address the above feedbacks and/or unchecked acceptance criteria - if you need guidance , please refer to the `README.md` file.

**Comment by AnshMeshram** [comment]
Adding animation card results
Capture
please accept the request

**Comment by AnshMeshram** [comment]
Pleas  review  and accept my pull request

**Comment by LaurelineP** [comment]
@AnshMeshram  Unfortunately this still cannot be merged as you pasted in your PR
but it requires to be within the project in your folder named after your github username.
+ you capture the frame of your browser when we require to have just a capture of the animation / result of your animation in picture ( no browser should be visible - you could crop the picture )

**Comment by AnshMeshram** [comment]
Ok

**Comment by LaurelineP** [comment]
@AnshMeshram  Please address the feedbacks 
- add a screenshot or gif of your animated result
- add your contribution details into the `include.js` file

**Pull request closed without merging**
