### PR TITLE
added sky animation

### PR DESCRIPTION
**Pull request by RoksolanaVeres**

### CODE REVIEW

**Comment by LaurelineP** [comment]
Thanks for your contributions :) 
Here are some feedbacks to address before we could merge it.

# Feedbacks
- [ ] missing modifications in `include.js`
- [ ] unnecessary file to remove : file with .wmv extension

If you need guidances, please refer to the readme file - you'll have all the details :)

**Comment by RoksolanaVeres** [comment]
Hello @LaurelineP , thank you for reviewing my PR! I have fixed the problems, mentioned in your comment, could you please review my changes again?

**Comment by LaurelineP** [comment]
@RoksolanaVeres 
Hi there :) unfortunately your are still missing the adjustments in `include.js` file
Please apply the recommended changes on the `include.js` file that is not present in your PR

**Comment by RoksolanaVeres** [comment]
@LaurelineP 
Excuse me, could you please clarify which exact changes I have to make in the include.js file? I haven't changed any file names. After my latest changes, I'm no longer adding/removing/renaming any files, I just changed the content of the gif file but it has the same name as it had previously ("moody-sunflower.gif"), and all the other information provided there like my artName, pageLink, imageLink, author and githubLink is still valid

**Comment by LaurelineP** [comment]
@RoksolanaVeres  My bad - I though it was your first contribution.
All good to go if this is already there.
Maybe what you could do if adjust some work is to leave a message clarifying what the contribution is about ( example : "adjusting/modifying my existing contribution" :) 

Thanks for your reactivity !🙌

**Pull request merged**
