### PR TITLE
Added my file in Art folder which include my animation html,css,gif

### PR DESCRIPTION
**Pull request by BlueHeart0065**
Added files (gun.html , gun.css , gun.gif) in the Art folder and modified include.js by adding my details in it.

### CODE REVIEW

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Hey @BlueHeart0065 
Nice job so far on the animation. Unfortunately I am unable to merge this PR as it removes another students directory. 

If you could address this issue we can go ahead and merge the PR

**Comment by BlueHeart0065** [comment]
Requested changes applied

**Comment by MattCSmith** [comment]
> Requested changes applied

@BlueHeart0065 Unfortunately I am still seeing the files as deleted in the Files changed tab :(

**Comment by BlueHeart0065** [comment]
Ill try again

**Comment by BlueHeart0065** [comment]
Hey Matt , I guess I resolved the merge issue now

**Review by MattCSmith — APPROVED** [review]
Looks good to me. Nice job 👍

**Pull request merged**
