### PR TITLE
Text Rotation Animation 

### PR DESCRIPTION
**Pull request by Rajneesh2223**
I have added a new text rotation animatiion

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Is this a new entry/contribution or a change?

Your pull request is named "Text rotation animation", but the newly added artwork is a colored bouncing ball.

Each contribution needs a _separate_ entry in `include.js`, so if this is a new contribution, you need to add a new entry.

The artwork needs to be in a folder that has the same name as your Github username. Currently it's in `Art/colourchange` instead of `Art/Rajneesh2223`.

Please see the [Guide in README.md](https://github.com/zero-to-mastery/Animation-Nation#how-to-contribute) for further details.

##  Checklist
- [x] created a submission into the `./Art` folder
- [ ] the contribution folder in `./Art` is the contributor's Github name
- [x] has a gif or png file of the animation
- [x] can find the html 
- [x] can find the style (css file)
- [ ] modified `include.js` **with the right details**

## Issues: 

- unclear if the entry in `include.js` is correct.

Please refer to the `README.md` file for guidance and follow the guidelines.
If you have questions feel free to reach to the discord or ask them here.

**Review by Rajneesh2223 — COMMENTED** [review]
{
    artName: 'colourchange',
    pageLink: './Art/colourchange/index.html',
    imageLink: './Art/colourchange/textAnimation.gif',
    author: 'Rajneesh Kumar',
    githubLink: 'https://github.com/Rajneesh2223',
  },

**Comment by LaurelineP** [comment]
@Rajneesh2223 
the contribution remains invalid - the folder you are proposing should be named after your github unique user name

**Comment by l-white** [comment]
Closing PR due to inactivity

**Pull request closed without merging**
