### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by PentesterPriyanshu**
i have created a contributing.md file which is missing in this repo i hope this is good  if you want any changes tell to me

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
@LaurelineP  look at this file

**Comment by LaurelineP** [comment]
Thanks for your contribution @PentesterPriyanshu  :) and great suggestion.
I have already seen your contribution ( cf: my PR you commented ) 

It is indeed a good practice to have the contributions files - that is actually where it should be done on production based repository - However, our ZTM repositories are already dedicated folders for contributions which explains why the rules are in the README.md file.
Note : the repository standards at github and others version control services,  
is to display on the repository page  the `README.md` file.
The team did choose to list the rules directly in it probably because our ztm repo are contributions oriented projects - except for the teachers / courses repositories .

Also, having 2 files to list the rules ( in ztm contributions oriented project ) could be, in our case, a duplication of "file concern or directives" if I can say,
which does not help any person reading the repository structure as it could be confusing.

I will double check with my peers before acting on your PR, but on my end 
this PR should not be merged because of the explanations above

**Comment by PentesterPriyanshu** [comment]
@LaurelineP  i think then we have to edit readme file and seperate all stuff of contributing.md 
because as i also have contributed to this project earlier i missed guidelines so seperating contributing.md is always makes repo clean and eye catchy

**Comment by sophiabrandt** [comment]
You can argue the other way round. If the contribution guidelines are in a different file, it's even more unlikely that people will read them.

On the other hand, it's clearly expected of you to read the README file, and AFAIK it's also what Andrei teaches in his courses.

So while we _really_ appreciate the thought that you put into this, we are currently not willing to merge this into the repo.

**Pull request closed without merging**
