### PR TITLE
i have added new animation project

### PR DESCRIPTION
**Pull request by PentesterPriyanshu**
In this example, i have added a new animation called `pulse-scale` that scales the `cube-corner` elements up and down when they are hovered over.i  have also added a new animation called `shadow-pulse` that animates the shadow of the `cube-corner` elements when they are hover

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
@LaurelineP  merge this or comment any problem

**Comment by PentesterPriyanshu** [comment]
@LaurelineP  merge this pr or any problem in this also

**Comment by PentesterPriyanshu** [comment]
@l-white   @LaurelineP

**Comment by PentesterPriyanshu** [comment]
@l-white   is anyone here

**Comment by PentesterPriyanshu** [comment]
@LaurelineP  i have resolved all conflicts please merge it ,thank you

**Comment by LaurelineP** [comment]
Hi there, 
please do not post several comments and do not ping several times people 
- this is not the way you want to work with colleagues.

According to the github changes you did not address the feedback I gave regarding your gif file naming.
Please try to pay attention on the feedback we take time to give to address before reaching out again.
Please scroll above and address the feedback.

Thanks

**Comment by PentesterPriyanshu** [comment]
> Hi there, please do not post several comments and do not ping several times people
> 
>     * this is not the way you want to work with colleagues.
> 
> 
> According to the github changes you did not address the feedback I gave regarding your gif file naming. Please try to pay attention on the feedback we take time to give to address before reaching out again. Please scroll above and address the feedback.
> 
> Thanks

sorry , if have violated any norms

**Comment by PentesterPriyanshu** [comment]
@LaurelineP sorry for tagging you earlier i have also changed the name of my gif folder as requested by you now merge it i have made total 17commits and also told you about previous merge pull which has wrong format

**Comment by LaurelineP** [comment]
Thanks for your contribution and reactivity 🙌

# Feedbacks
The contribution will be merged

## Acceptance criteria for a contribution
- [x] the contribution includes a new folder named after the author github user name  in `./Art`
- [x] the contribution includes an HTML file
    - [x] no CSS
    - [x] no JS
    - [x] no embedded  SVG 
    - [x] has a `<link>` tag to the CSS file
- [x] the contribution includes a CSS file
- [x] the contribution includes the animated file (gif) or picture (jpeg, jpg, png )
    _the pictural representation must not include the browser frame, just the animation_
- [x] the contribution includes the correct contribution's details in `include.js`

**Pull request merged**
