### PR TITLE
Kenimation

### PR DESCRIPTION
**Pull request by kennedy-ogutu**
Please add my y animation to this list.

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Why are you deleting the files from a different user?

**Comment by kennedy-ogutu** [comment]
Hi Sophia, I was trying to use some of the  code and realised it wasn't possible. I tried to revert those changes but I don't know how to do it.

**Comment by sophiabrandt** [comment]
You should have Node.js on your computer. Then run `npx prettier -w include.js` inside the folder and fix the syntax errors.
Please don't forget to [sync your fork to upstream](https://short.pm/forksync).

**Comment by sophiabrandt** [comment]
Maybe this helps: https://www.git-tower.com/learn/git/faq/restoring-deleted-files/

**Comment by kennedy-ogutu** [comment]
Hi Sophia, I managed to restore all the changes I made on the other user, my question, do I need to do a commit and push to restore the changes on github.
Regards

**Pull request closed without merging**
