### PR TITLE
Added Square shape color changing animation

### PR DESCRIPTION
**Pull request by divyansharya8826**

### CODE REVIEW

**Comment by LaurelineP** [comment]
Thanks for your contribution 🙌
Before we could merge your contribution, the following feedbacks need to be addressed first.
Please address the given feedbacks

# Feedbacks  
➡️ Unused pictural file and missing the contribution in `include.js` file
- [ ] gif file - keep the one you will specify in the `include.js` file and remove the unused one
- [ ] missing contributions in `include.js` file

## Acceptance criteria for a contribution
- [x] the contribution includes a new folder named after the author github user name  in `./Art`
- [x] the contribution includes an HTML file
    - [x] no CSS
    - [x] no JS
    - [x] no embedded  SVG 
    - [x] has a `<link>` tag to the CSS file
- [x] the contribution includes a CSS file
- [x] the contribution includes the animated file (gif) or picture (jpeg, jpg, png )
    _the pictural representation must not include the browser frame, just the animation_
- [ ] the contribution includes the correct contribution's details in `include.js`

Please address the above feedbacks and/or unchecked acceptance criteria - if you need guidance , please refer to the `README.md` file.

**Comment by divyansharya8826** [comment]
I have done all the instructions mention in the readme.md file then why my PR was not accepted yet.

**Comment by LaurelineP** [comment]
Based on the current changes in your PR and the feedback I gave you 
>  - [ ] gif file - keep the one you will specify in the include.js file and remove the unused one
> -  [ ] missing contributions in include.js file

None of the above were changed --> see [your pr changes tab]("https://github.com/zero-to-mastery/Animation-Nation/pull/2277/files")
There are no changes on the `include.js` file ( which will be responsible to display your contribution - hence this is why your PR is still not valid 
-> 2 feedbacks not addressed

**Comment by divyansharya8826** [comment]
> @divyansharya8826 Based on the current changes in your PR and the feedback I gave you
> 
> > * [ ]  gif file - keep the one you will specify in the include.js file and remove the unused one
> > * [ ]  missing contributions in include.js file
> 
> None of the above were changed --> see your pr changes tab There are no changes on the `include.js` file ( which will be responsible to display your contribution - hence this is why your PR is still not valid -> 2 feedbacks not addressed

I have completed the above feedback instructions. Now, can you accept my PR.

**Pull request merged**
