### PR TITLE
added my art

### PR DESCRIPTION
**Pull request by Upendra2003**

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Thanks for this contribution.

Please check the following checklist that you need to fulfill for us to be able to merge your request.

Please see the [Guide in README.md](https://github.com/zero-to-mastery/Animation-Nation#how-to-contribute) for further details.

##  Checklist
- [x] created a submission into the `./Art` folder
- [ ] the contribution folder in `./Art` is the contributor's Github name
- [x] has a gif or png file of the animation
- [x] can find the html 
- [x] can find the style (css file or inline)
- [x] modified `include.js` **with the right details**

## Issues: 

- Please change your art folder name to the name of your _Github username_ - this helps us to avoid confusion and duplicates. Thanks!
- Don't forget to update `include.js` after you have renamed your folder.

If you have questions feel free to reach out on the discord channel #hacktoberfest-2023 or ask them here in this pull request.

**Comment by LaurelineP** [comment]
Thanks for your contribution 🙌
Before we could merge your contribution, the following feedbacks need to be addressed first.
Please address the followings

# Feedbacks  
Your folder is not correctly named after your unique github username, 
please adjust it and make this addresses the following criterions 
## Acceptance criteria for a contribution
- [ ] the contribution includes a new folder named after the author github user name  in `./Art`
- [x] the contribution includes an HTML file
    - [x] no CSS
    - [x] no JS
    - [x] no SVG
    - [x] has a `<link>` tag to the CSS file
- [x] the contribution includes a CSS file
- [x] the contribution includes the animated file (gif) or picture (jpeg, jpg, png )
    _the pictural representation must not include the browser frame, just the animation_
- [ ] the contribution includes the correct contribution's details in `include.js`

Please address the above feedbacks - if you need guidance , please refer to the `README.md` file.

**Comment by Upendra2003** [comment]
> Thanks for this contribution.
> 
> Please check the following checklist that you need to fulfill for us to be able to merge your request.
> 
> Please see the [Guide in README.md](https://github.com/zero-to-mastery/Animation-Nation#how-to-contribute) for further details.
> 
> ## Checklist
> * [x]  created a submission into the `./Art` folder
> * [x]  the contribution folder in `./Art` is the contributor's Github name
> * [x]  has a gif or png file of the animation
> * [x]  can find the html
> * [x]  can find the style (css file or inline)
> * [x]  modified `include.js` **with the right details**
> 
> ## Issues:
> * Please change your art folder name to the name of your _Github username_ - this helps us to avoid confusion and duplicates. Thanks!
> * Don't forget to update `include.js` after you have renamed your folder.
> 
> If you have questions feel free to reach out on the discord channel #hacktoberfest-2023 or ask them here in this pull request.

**Comment by Upendra2003** [comment]
> Thanks for your contribution 🙌 Before we could merge your contribution, the following feedbacks need to be addressed first. Please address the followings
> 
> # Feedbacks
> Your folder is not correctly named after your unique github username, please adjust it and make this addresses the following criterions
> 
> ## Acceptance criteria for a contribution
> * [x]  the contribution includes a new folder named after the author github user name  in `./Art`
> * [x]  the contribution includes an HTML file
>   
>   * [x]  no CSS
>   * [x]  no JS
>   * [x]  no SVG
>   * [x]  has a `<link>` tag to the CSS file
> * [x]  the contribution includes a CSS file
> * [x]  the contribution includes the animated file (gif) or picture (jpeg, jpg, png )
>   _the pictural representation must not include the browser frame, just the animation_
> * [x]  the contribution includes the correct contribution's details in `include.js`
> 
> Please address the above feedbacks - if you need guidance , please refer to the `README.md` file.

**Comment by Upendra2003** [comment]
merge this !!

**Comment by Upendra2003** [comment]
Resolved all conflicts merge this !!

**Pull request closed without merging**
