### PR TITLE
Added Blooming flower animation

### PR DESCRIPTION
**Pull request by Asymtode712**

### CODE REVIEW

**Comment by Asymtode712** [comment]
Please review my request

**Comment by LaurelineP** [comment]
Thanks for your contributions  @Asymtode712 ! 🙌

## Feedbacks
Please address the following in order to merge those
- [ ] **file naming:** 
for each contributions you did please review the file containing 
 a space in their names: replace the space by an hyphen or underscore
Space in file or folder naming are not standard and to avoid any side effects it is better to apply the above

After those elements addressed, this will be good for a merge :)

**Comment by Asymtode712** [comment]
@LaurelineP I have done the changes as directed by you. Please review my request

**Comment by Asymtode712** [comment]
@LaurelineP  I have done the changes as directed by you and also updated include.js . Please review my request

**Comment by LaurelineP** [comment]
@Asymtode712 All good for me - once again thanks both for your contributions ( nice arty skills you have ) and your reactivity 🙌

**Pull request merged**
