### PR TITLE
Animated Timeline

### PR DESCRIPTION
**Pull request by kishan-25**
**What I did**
I created an Animated Timeline using HTML and CSS. This timeline features alternating events that slide in from the left and right sides of the page as the user scrolls, simulating a chronological sequence of project phases. Each event includes animation for smooth transitions to enhance visual appeal and user experience.

**Pull request checklist**

-  This pull request uses HTML and CSS only.
-  All files in this pull request are in a directory named: your_github_username-animated_timeline without the <>.
-  Your pull request contains only index.html and styles.css.
-  Your html file is named exactly: index.html.
-  Your css file is named exactly: styles.css.
-  Your submission includes at least one animation (timeline event sliding animations).
-  Your pull request does not modify any other files in the repository.

### CODE REVIEW

**Review by kazdj21 — CHANGES_REQUESTED** [review]
As I have said in your previous PR, please stick to one animation per PR so that we can ensure that our github actions configurations can do its job.

**Comment by kishan-25** [comment]
@kazdj21 Sir/Mam i created a new pr for this animation plz review it and let me know is everything fine or i need to make any changes . Thanks for your assistance .

**Review by kazdj21 — CHANGES_REQUESTED** [review]
Currently, the PR still shows 6 files. Please stick to one animation project per PR.

**Comment by LaurelineP** [comment]
_From the README.md_
> You can contribute multiple animations, Just create a new directory with your < github_username>-

@kazdj21  We can accept multiple animations according to the guidelines as long as they respects th
So if the projects are respecting all the others points I you could merge if you'd like to.

**Comment by kazdj21** [comment]
> _From the README.md_
> 
> > You can contribute multiple animations, Just create a new directory with your < github_username>-
> 
> @kazdj21 We can accept multiple animations according to the guidelines as long as they respects th So if the projects are respecting all the others points I you could merge if you'd like to.

I see. For the sake of being able to rollback cleanly though, as I've mentioned in the maintainers discord chat, I feel like we should stick to a PR per animation. Also currently, the user has duplicated code across many of their PRs.

**Review by kazdj21 — APPROVED** [review]
Okay! Looks good to me.

**Pull request merged**
