### PR TITLE
Added a new animation : "Bouncing Ball with colour change"

### PR DESCRIPTION
**Pull request by Vivek-GuptaXCode**
bouncing-ball

### CODE REVIEW

**Comment by Vivek-GuptaXCode** [comment]
please look into the PR,suggest changes if any.

**Comment by LaurelineP** [comment]
Hi there : thanks for your contribution 🙌
Here are some feedbacks to address before we could merge it

# Feedbacks
- [ ] extra html file.  
It looks like you have an extra html file that you do not use : `index.html`.  
Make sure to remove it if not used :)

**Comment by Vivek-GuptaXCode** [comment]
Please review the changes made,have a great day!!

**Comment by Vivek-GuptaXCode** [comment]
@LaurelineP i hope u are in good health.can u please review the PR as i have made all the desired changes.i appreciate your efforts.

**Pull request merged**
