### PR TITLE
Background-line-animation

### PR DESCRIPTION
**Pull request by Hrishap**
abstract line animation for background

### CODE REVIEW

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Hey @varshithab05 
Great job on the animation so far, its looking awesome. 
I'm unable to merge this PR currently as your missing the includes.js file. 

If you could include this file we'll be able to proceed and merge you pull request :)

**Comment by Hrishap** [comment]
@MattCSmith sir
thank you for stating my mistake 
i will make sure not to create any problems in future 
again thank u:)

**Comment by Hrishap** [comment]
respected changes done

**Review by MattCSmith — APPROVED** [review]
Looks good to me. Nice job 👍

**Pull request merged**
