### PR TITLE
First Simple loading animation

### PR DESCRIPTION
**Pull request by SaiAryan1784**

### CODE REVIEW

**Comment by l-white** [comment]
@SaiAryan1784 Please include a gif for your animation and your details in the include.js file. See the README on this repo for those instructions. If you need further assistance, you can ask for help in the #hacktoberfest-2023 channel in the Zero to Mastery Discord server.

**Comment by SaiAryan1784** [comment]
@l-white hi is this ok now pls do check

**Comment by LaurelineP** [comment]
Note to other maintainers 
- `master` already did merge the first commit with the folder `Art/Sai` containing the 3 files
- current MR: includes : `include.js` modifications
The modifications are partly on main and in this MR for the include details but seems all good.

Checked `Art/Sai` contribution 
  - has gif _( was merged in master )_ 
  - has html _( was merged in master )_ 
  - has css _( was merged in master )_ 
  - added details in `include.js`
 
 Good to merge > will merge

**Comment by LaurelineP** [comment]
Mistake on my hand: confused "commend and close" and "comment"
hence the reopening of the MR

**Pull request merged**
