### PR TITLE
Mood  swing animation

### PR DESCRIPTION
**Pull request by apu52**
I have added a new animation project named mood swing animation.
I have made it using HTML & CSS
Can you please review it & please merge it??

### CODE REVIEW

**Comment by apu52** [comment]
@l-white @sophiabrandt Please take a review of my PR & merge it.

**Comment by LaurelineP** [comment]
@apu52 thanks again for this new contribution however we cannot currently merge your project as your contribution does not follow all the acceptance criterions .

## Criterions according to your contribution
- [ ] created a submission into the `./Art` folder
- [ ] the contribution folder in `./Art` is the contributor name
- [ ] has a gif file of the animation
- [x] can find the html 
- [x] can find the style
- [x] modified `include.js`

## Issues: 

- you've created a folder at the project's root level whereas it should be **within** the folder "Art"
- above point does not reflects in `include.js`: the referenced relative paths are incorrect based on the contribution having the folder "Funky Boy" being at `./Kaleidoscope` and not at `apu52` as described in the `include.js`: 
 - there are no folder "apu52" folder in "Art" folder
 - the paths does not match your `include.js` contribution
```js
 {
    artName: 'Mood Swing',
    pageLink: './Art/apu52/index.html',
    imageLink: './Art/apu52/mood swing.png',
    author: 'Arpan Chowdhury',
    githubLink: 'https://github.com/apu52'
  },
```

Please refer to the `README.md` file for guidance and follow the guidelines.

## Feedbacks
Here are some guidance:
- have your contribution within the folder `./Art`
- make sure `includes.js` contribution refers to the correct path to your project within the folder `./Art`
- make sure it that you push a **gif** file and not a **mp4** file

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Please remove `.mp4` file from your commit

**Comment by MattCSmith** [comment]
Unfortunately we are unable to merge this pull request as it violates rule 3 of this project: 
`Please make sure that the code is indeed your own, and not copied from someone else`

https://www.youtube.com/watch?v=ixCGP4O6_WU

**Pull request closed without merging**
