### PR TITLE
Adding animation

### PR DESCRIPTION
**Pull request by hkxxx843**
Adding an animation.

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Please follow instructions in `README.md` on how to add your contribution to this repository. You will need to edit `include.js` file.

**Comment by hkxxx843** [comment]
> Please follow instructions in `README.md` on how to add your contribution to this repository. You will need to edit `include.js` file.

I included it already.

**Comment by sophiabrandt** [comment]
@hkxxx843 can you please point out where? If I take a look at the changed files (https://github.com/zero-to-mastery/Animation-Nation/pull/1082/files) I cannot see it. I've also checked out your repo locally, and "Harish" does not appear anywhere in `include.js`.

**Comment by hkxxx843** [comment]
@sophiabrandt  sorry I don't know what I forgot that changes are not there. Fixing it now. Thanks for your guidance.

**Pull request merged**
