### PR TITLE
Added animation solar system

### PR DESCRIPTION
**Pull request by Shubhamkashyap1601**
solar

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Duplicate of #2259 - please make the changes to the original pull request.

**Comment by Shubhamkashyap1601** [comment]
I have closed the original pull request
What should i do now?

**Comment by sophiabrandt** [comment]
I have reopened this. I will still consider this a valid submission as an exception. See rules in README.

**Comment by Shubhamkashyap1601** [comment]
Thankyou 😃

**Pull request merged**
