### PR TITLE
adding my art to the project

### PR DESCRIPTION
**Pull request by austincomstock**
Please add me to this list.

### CODE REVIEW

**Review by donmarvex — CHANGES_REQUESTED** [review]
Hello @austincomstock , could you make a crop you GIF to only include the robot as it is being animated. This full screen display when rendered in the web application would be quite difficult to see. Thanks

**Comment by austincomstock** [comment]
Hello, I have updated the .gif file, thank you.

**Comment by donmarvex** [comment]
> Hello, I have updated the .gif file, thank you. @donmarvex

Alright. It looks great @austincomstock . I noticed you have closed the pull request but it's yet to be merged? Do you intend to open another PR to push your work to the project? 
If not, I will reopen and merge your changes.

**Comment by austincomstock** [comment]
Hi @donmarvex,

If you could reopen and merge that would be great. Thank you!

- Austin Comstock

**Pull request closed without merging**
