### PR TITLE
Made a simple meme animation lol

### PR DESCRIPTION
**Pull request by rahulnegi20**
This is my first contribution in this repo, do let me know if you like it!

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
This pull request is not complete. Please read the guide on how to contribute to this repo in the README file.
You have to add your animation to the `include.js` file.

**Comment by rahulnegi20** [comment]
Hey but i have not anything to write in script in js! what i'm supposed to do now

**Comment by sophiabrandt** [comment]
Please read the guide on how to contribute to this repo, and do step 6: https://github.com/zero-to-mastery/Animation-Nation#how-to-contribute

**Comment by rahulnegi20** [comment]
Hey! Check this out moderator, is it good to merge now?

**Pull request merged**
