### PR TITLE
Animated 2024

### PR DESCRIPTION
**Pull request by Kaif-Azmi**
Thank you for making a pull request to ZTM's Animation Nation project. We will review your pull request as soon as we can, but keep in mind we can get very busy during Hacktoberfest.

While you're waiting, please look over this checklist. Feel free to write a description of what you did as well!

## What I did

I have animated "2024" as we are loosing it slowly.

## Pull request checklist

- [x] This pull request uses **HTML and CSS** only and provides a `meta.json` file.
- [x] All files in this pull request are in a directory named: `Kaif-Azmi-Animation-Done` without the <>.
- [x] Your pull request contains `index.html` and `styles.css`.
	- [x] Your html file is named exactly: `index.html`
	- [x] Your css file is named exactly: `styles.css`
- [x] Your pull request your `meta.json` with:
	- [x] `githubHandle`: being your unique github user name,
	- [x] `artName` : name of your animation
- [x] Your submission includes **at least one animation**.
- [x] Your pull request **does not modify any other files** in the repository.

#### Not normally needed
- [x] Check this if you would like to discuss an improvement besides adding animations

**Note: if your pull request makes an improvement besides adding a CSS animation you will need to discuss this with the maintainers. You can help kickstart this process by explaining what your change does and why you are making it in the "What I did" section**

## What to expect

- If your pull request meets the checklist requirements it will be approved and merged by a maintainer
- If your pull request needs some changes. A maintainer will leave a comment requesting changes
- If your pull request significantly violates the criteria in the checklist it will be closed with feedback.

### CODE REVIEW

**Comment by Kaif-Azmi** [comment]
Thank you @maintainers, because of you i learned git, github and CSS.

**Comment by LaurelineP** [comment]
Aloha @Kaif-Azmi 
- [ ] Please remove all duplicated folder 
- [ ] Please ping me back once done so I can review once your PRs is not duplicated
image

**Comment by Kaif-Azmi** [comment]
Fixed all the issues please review.

**Comment by LaurelineP** [comment]
@Kaif-Azmi 
In the previous feedbacks I've mentioned :
- you probably created on top of branch the animations folders or you did not update your local branch correctly
- which led git to track those folder as new folders

I've asked:
- to remove the duplicated folders indeed - but not deleting from Art : it meant to untrack them in your PRs and make sure your machine is up to date with the (distant) repo.
I've seen your action on manually updating your PR - but this is done in the distant repository 
If you do not :
- git pull your branch ( remote one ) 
- and not rebasing `master` on your branch master and your development branch 
The changes will remains tracked and possibly on you will get conflict 

We need a branch for inexistant folders contributions:
Once your project is up to date with the remote repo
If Art contains any folders Kaif-Azmi-<title> : these corresponds to the already merged ( accepted prior PR ) 
Your new PR should only contain the new folder you want to add.
According to current code in master - these are already existing
image

But this PR is  ⚠️**DELETING the existing ones from master**⚠️ and add a new one - been Animation-Done
image



What can be done ( easier way after this explaination ) 
- in your local branch delete the folders manually ( with your mouse to keep it simple )
- then you will commit the change "Feedback : Removed the two folders from local machine"
- then you will execute on the branch and in your terminal `git pull --rebase origin master` ( which will apply all missing changes from the distant repo to your machine ) - hopefully you don't get errors otherwise you will need to resolve the conflicts
   - Once successful: you local project ( on your machine ) at the branch your are developing in: you should 
   get the folders back
   - just to check if this causes any changes you can run `git status` and ensure there are no changes - if they are - it would mean you've handled conflicts ) which should be commited if any - but unsure it remains untracked
   
   Easier way would be to 
   - get rid of that branch current PR ( close it )
   - checkout locally to master
   - `git pull` to update your project with the repo updates
   - create a new branch from that freshly updated master
   - add ONLY the new contribution folder with its file ( 3 files = index.html, meta.json, styles.css ) with your animation content
   - then `git push`

**Pull request closed without merging**
