### PR TITLE
Added Favicon #1869

### PR DESCRIPTION
**Pull request by SimardeepSingh-zsh**

### CODE REVIEW

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Hey @SimardeepSingh-zsh 
Thanks for the PR to improve the website by adding a favicon
Unfortunately I am not able to merge this currently as the link references a image file that does not exist. 

Perhaps you could create the favicon.ico and add it to this PR, so we can merge.

**Comment by MattCSmith** [comment]
Just checking in on this PR and noticed the PR still doesn't include and image. 
If you need help please feel free to reach out in the #hacktoberfest channel over on Discord

**Review by SimardeepSingh-zsh — COMMENTED** [review]
This is a valuable addition! Favicon provides a small yet essential touch to the project's overall user experience. It helps in branding and differentiating your website.

- [x] Favicon "ZTM_SimardeepSingh-zsh.ico" has been added.
- [x] It appears to be properly formatted and in the appropriate location.

Nice work on enhancing the project! This is a small detail, but it contributes to the overall professionalism and user-friendliness of the site.

**Comment by MattCSmith** [comment]
> This is a valuable addition! Favicon provides a small yet essential touch to the project's overall user experience. It helps in branding and differentiating your website.
> 
> * [x]  Favicon "ZTM_SimardeepSingh-zsh.ico" has been added.
> * [x]  It appears to be properly formatted and in the appropriate location.
> 
> Nice work on enhancing the project! This is a small detail, but it contributes to the overall professionalism and user-friendliness of the site.

Hey @SimardeepSingh-zsh 
Unfortunately I am still unable to merge this PR and its not yet complete. 
You have added the line of code on the index page for the Favicon, but it references an image that does not exist. 
The favicon code must reference an actual image within the project and there is not a file called "ZTM_SimardeepSingh-zsh.ico" in your pull request or already in the project. 

If you need more help with this, please reach out in our #hacktoberfest channel on Discord.

**Comment by sophiabrandt** [comment]
Missing file added in #2362 instead of this PR 🤷

**Pull request merged**
