### PR TITLE
adding my heart to the project :)

### PR DESCRIPTION
**Pull request by MishkaZi**
Added animation to the project! Thanks

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Please don't add git submodules to this project. Please follow the guide in the README and add your artwork to the `Art` folder.

**Comment by MishkaZi** [comment]
Thank you very much, please tell me if I done everything correctly.

**Comment by sophiabrandt** [comment]
@MishkaZi Hello, as far as I can see, you are still adding your art as a git submodule. Can you please fix that?
https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule

**Comment by MishkaZi** [comment]
I deleted .git submodule from my subfolder in Art. I hope that will work now

**Comment by sophiabrandt** [comment]
Hi @MishkaZi, thanks for answering. It still looks like your artwork is only available as a git submodule.
I think at this point it might make more sense to start fresh?

**Comment by MishkaZi** [comment]
Yes, thanks, I will start over

**Pull request closed without merging**
