### PR TITLE
Added dynamic Letter Animation template

### PR DESCRIPTION
**Pull request by varshithab05**
This project introduces a captivating dynamic letter animation template created using HTML and CSS. The animation effect is designed to provide a visually engaging experience.

I welcome your feedback, suggestions, and contributions to further improve the template and the repository as a whole.

### CODE REVIEW

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Hey @varshithab05 
Great job on the animation so far, its looking awesome. 
I'm unable to merge this PR as it currently removed 533 lines from the includes.js file. 

If you could resolve this issue we can proceed and merge your PR

**Comment by MattCSmith** [comment]
Hey @varshithab05 
Just checking in on this PR again and I still see a large number of deletions preventing me from merging. 
If you need help please feel free to reach out in the #hacktoberfest channel over on Discord

**Comment by LaurelineP** [comment]
# To my peer maintainers
Rebases issues manually handled and double checked
- removed duplicated contribution
- ensured varshithab05 contributions
Consciously merging the MR with that amount of contribution duplicated

**Comment by LaurelineP** [comment]
To my peer maintainers:
Dove into checking duplications - still found some
How I checked:
- from PR code - copy the entire cards variable ( length of 262 )
- creating a stringified version of cards ( length of 262 )
- created a new variable and remove duplicates with `new Set` ( length of 197 )
Hence the amount of removed lines most likely
Also checked again if I could read duplicated - and yes I could read some

Added a commit to replace cards with the array obtained by removing duplicates

**Pull request merged**
