### PR TITLE
Update include.js

### PR DESCRIPTION
**Pull request by nharjes**
added info to include.js

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Is this the same as #2320 or related?

If not, then multiple files are missing.

**Comment by sophiabrandt** [comment]
If this is the same PR, please re-open the original one and add the required changes.

**Comment by nharjes** [comment]
@sophiabrandt  thanks for the review. adding the missing parts of the  PR #2320 didn't worked for me. This PR #2329 should  have fixed this , but didn't.  So i started everything from scratch an submitted the correctly named files in a new PR # 2335.  Maybe you can close this PR? and sorry for the chaos  ...still learning.

**Comment by sophiabrandt** [comment]
@nharjes the problem is that you know have two separate PRs that are both missing one or more files - vice versa.

Could you try to add the missing artwork to this PR, then? In this PR, there's only the `include.js` file, so all the other files (HTML, CSS, etc.) are missing.

**Comment by nharjes** [comment]
@sophiabrandt I added the missing files to this PR.  thank you!

**Pull request merged**
