### PR TITLE
I created Mantras Animation 

### PR DESCRIPTION
**Pull request by vikasgadge28**

### CODE REVIEW

**Comment by l-white** [comment]
@vikasgadge28 There are a number of div tags that are not closed in your HTML file. Please make those changes and commit them to this branch.

**Comment by vikasgadge28** [comment]
This is not any kind of error, this project itself has been created with its help, so please merge this pull request.

**Comment by vikasgadge28** [comment]
> @vikasgadge28 There are a number of div tags that are not closed in your HTML file. Please make those changes and commit them to this branch.



> @vikasgadge28 There are a number of div tags that are not closed in your HTML file. Please make those changes and commit them to this branch.

This is not any kind of error, this project itself has been created with its help, so please merge this pull request.

**Comment by vikasgadge28** [comment]
> @vikasgadge28 There are a number of div tags that are not closed in your HTML file. Please make those changes and commit them to this branch.

This is not any kind of error, this project itself has been created with its help, so please merge this pull request.

**Review by MattCSmith — APPROVED** [review]
Laura is correct, this pull request has several Div Tags that are not closed creating syntax errors. 
We are unable to merge this until it has been addressed.

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Please ensure all div tags are closed, so we can proceed to merge your Art

**Review by MattCSmith — APPROVED** [review]

**Pull request merged**
