### PR TITLE
Gradient Loader Animation

### PR DESCRIPTION
**Pull request by KartikeyMish**
This PR introduces a Gradient Loader Animation for the users so they use for their websites. Key updates include:

- [x]  Blue to Red Gradient color loader 
- [x]  Smooth & user can easily manipulate the loader colors.

Please review for design and performance.

GradientLoader

### CODE REVIEW

**Comment by KartikeyMish** [comment]
Please add the `hacktoberfest-accepted` label into this PR so that it is accepted in hacktoberfest.

**Review by MattCSmith — APPROVED** [review]
Looks good to me, nice job

**Comment by MattCSmith** [comment]
The Hacktoberfest-accepted label is only required if the Hacktoberfest label is not added to the repo

**Comment by KartikeyMish** [comment]
@MattCSmith okay thanks. :)

**Pull request merged**
