### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by rajmishra-47**
This is my first contribution to this repository
I am a beginner in web development

### CODE REVIEW

**Review by donmarvex — COMMENTED** [review]
Hello @rajmishra-47 , nice work with your largebox animation. Is there a way for you to crop out the menubars from your browser. The rendered GIF on the web application displays the following below
image

Other than that you're good to get merged!

**Comment by rajmishra-47** [comment]
> Hello @rajmishra-47 , nice work with your largebox animation. Is there a way for you to crop out the menubars from your browser. The rendered GIF on the web application displays the following below image
> 
> Other than that you're good to get merged!

**Comment by rajmishra-47** [comment]
> Hello @rajmishra-47 , nice work with your largebox animation. Is there a way for you to crop out the menubars from your browser. The rendered GIF on the web application displays the following below image
> 
> Other than that you're good to get merged!

should I re upload

**Comment by rajmishra-47** [comment]
Respected Sir,
 the previous PR was accidentally closed by me so I made the necessary
changes and opened a new PR is it ok

**Pull request closed without merging**
